### ISSUE TITLE
Make gists secret or have an option for that

### ISSUE THREAD

**Issue by Timothee** [Jarred-Sumner/styleurl-extension#15]
I'm not sure what there's much to gain from making public gists. (besides linking to them on your homepage) Right now I got a surprise to see that they were.

There should be at least an option to make gists secret.

Thanks!

(great app by the way!)

**Comment by Jarred-Sumner** [comment]
I agree with you, public gists by default was a mistake.

Fix incoming.

**Comment by Jarred-Sumner** [comment]
As of 1.1.13, new gists are always secret.

**Comment by Timothee** [comment]
Fantastic turnaround time! 👌🏻
Thanks!

Tim

Sent via Superhuman iOS ( https://sprh.mn/?vip=timothee@gmail.com )

**Comment by Jarred-Sumner** [comment]
np
